services:
  tirus-web:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tirus.ai
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tirus-ai.rule=Host(`tirus.ai`) || Host(`www.tirus.ai`)"
      - "traefik.http.routers.tirus-ai.entrypoints=websecure"
      - "traefik.http.routers.tirus-ai.tls=true"
      - "traefik.http.routers.tirus-ai.tls.certresolver=letsencrypt"
      - "traefik.http.services.tirus-ai.loadbalancer.server.port=3000"
networks:
  traefik:
    external: true